"""Cross-language database-compatibility proof, Kotlin -> Python direction.

`StateDbGoldenParityTest.kt` (android/core) proves the other direction --
that the Kotlin `StateRepository`/`StateDb` can open, read, and write a
`sync_state.db` file the real `src/state.py` created. This module proves the
mirror image: that `src/state.py` can open and read a `sync_state.db` file
written by the real Kotlin `StateRepository`/`SqliteJdbcStateDb` path, with
no migration surprises and no `PRAGMA user_version` disagreement.

The fixture (`tests/fixtures/state_fixture_kotlin_written.db`) is generated
by `android/core/src/fixtureGen/kotlin/.../StateFixtureGenerator.kt`, a
one-off entry point run by hand with:

    cd android && ./gradlew :core:generateStateFixtureKotlinWritten

It is never regenerated by CI, and this whole module is skipped (not
failed) if the fixture is absent -- e.g. on a checkout where nobody has run
that Gradle task yet -- so its absence never blocks `pytest` for anyone
working on the Python side alone.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from src import state

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "state_fixture_kotlin_written.db"

pytestmark = pytest.mark.skipif(
    not _FIXTURE_PATH.exists(),
    reason=(
        "state_fixture_kotlin_written.db not present -- run "
        "'cd android && ./gradlew :core:generateStateFixtureKotlinWritten' to generate it"
    ),
)


@pytest.fixture
def kotlin_db_path(tmp_path: Path) -> Path:
    # Copy out of tests/fixtures/ so nothing here ever writes into a
    # committed file -- same pattern as db_path in conftest.py, just seeded
    # from the Kotlin-written fixture instead of starting empty.
    dest = tmp_path / "sync_state.db"
    shutil.copyfile(_FIXTURE_PATH, dest)
    return dest


def test_reads_every_row_the_kotlin_generator_wrote_exactly(kotlin_db_path):
    frozen_now = "2025-03-14T09:40:00"

    priya = state.get_chat("chat_priya", kotlin_db_path)
    assert priya["display_name"] == "Priya Nair"
    assert priya["source_filename"] == "Priya Nair.txt"
    assert priya["gmail_thread_id"] == "thread-kotlin-1"
    assert priya["gmail_label_id"] == "WhatsApp/Priya Nair"
    assert priya["anchor_message_id"] == "<kotlin-golden-anchor@local>"
    assert priya["created_at"] == frozen_now
    assert priya["updated_at"] == frozen_now

    rohan = state.get_chat("chat_rohan", kotlin_db_path)
    assert rohan["display_name"] == "Rohan Mehta"
    assert rohan["gmail_thread_id"] is None

    assert len(state.list_chats(kotlin_db_path)) == 2

    last_run = state.get_last_successful_run("chat_priya", kotlin_db_path)
    assert last_run["status"] == "complete"
    assert last_run["trigger"] == "manual"
    assert last_run["last_synced_ts"] == "2025-03-14T09:41:30"
    assert last_run["messages_parsed"] == 2
    assert last_run["messages_synced"] == 2
    assert last_run["messages_skipped"] == 0
    assert last_run["messages_cutoff"] == 0
    assert last_run["started_at"] == frozen_now
    assert last_run["completed_at"] == frozen_now

    h1 = state.compute_message_hash(
        "chat_priya", "2025-03-14T09:41:00", "Priya Nair", "hello from the kotlin-written fixture",
    )
    h2 = state.compute_message_hash(
        "chat_priya", "2025-03-14T09:41:30", "Meera Iyer", "line one\nline two",
    )
    assert state.hash_exists(h1, kotlin_db_path)
    assert state.hash_exists(h2, kotlin_db_path)
    assert state.get_hashes_for_run(last_run["run_id"], kotlin_db_path) == {h1, h2}
    assert last_run["last_synced_hash"] == h2

    pending = state.get_pending_runs(kotlin_db_path)
    assert all(row["chat_id"] != "chat_rohan" for row in pending)

    recent = state.get_recent_runs(days=3650, db_path=kotlin_db_path)
    rohan_runs = [row for row in recent if row["chat_id"] == "chat_rohan"]
    assert len(rohan_runs) == 1
    assert rohan_runs[0]["status"] == "failed"
    assert rohan_runs[0]["trigger"] == "watched_folder"
    assert rohan_runs[0]["error_message"] == "kotlin-written fixture: simulated network error"

    assert state.get_chat_cutoff("chat_priya", kotlin_db_path) == "2025-01-01T00:00:00"
    assert state.get_chat_cutoff("chat_rohan", kotlin_db_path) is None

    senders = {row["sender"]: row for row in state.list_chat_senders("chat_priya", kotlin_db_path)}
    assert senders["Priya Nair"]["msg_count"] == 1
    assert senders["Meera Iyer"]["msg_count"] == 1
    assert senders["Rohan Mehta"]["msg_count"] == 0

    assert state.get_app_state(state.SELF_SENDER_LEARNED, kotlin_db_path) == "Priya Nair"


def test_python_can_extend_a_kotlin_written_database_without_disturbing_it(kotlin_db_path):
    # Write: a brand-new chat, a completed run, a hash, a cutoff -- through
    # the ordinary Python write path, against a file Kotlin created.
    state.upsert_chat("chat_kavya", "Kavya Menon", "Kavya Menon.txt", db_path=kotlin_db_path)
    run_id = state.start_sync_run("chat_kavya", db_path=kotlin_db_path)
    new_hash = state.compute_message_hash(
        "chat_kavya", "2025-04-01T08:00:00", "Kavya Menon", "written by python",
    )
    state.insert_message_hashes(
        [(new_hash, "chat_kavya", "2025-04-01T08:00:00", run_id)], db_path=kotlin_db_path,
    )
    state.complete_sync_run(
        run_id,
        last_synced_ts="2025-04-01T08:00:00",
        last_synced_hash=new_hash,
        messages_parsed=1,
        messages_synced=1,
        messages_skipped=0,
        db_path=kotlin_db_path,
    )
    state.set_chat_cutoff("chat_kavya", "2025-04-01", db_path=kotlin_db_path)

    kavya = state.get_chat("chat_kavya", kotlin_db_path)
    assert kavya["display_name"] == "Kavya Menon"
    assert state.hash_exists(new_hash, kotlin_db_path)
    assert state.get_chat_cutoff("chat_kavya", kotlin_db_path) == "2025-04-01T00:00:00"

    # What Kotlin originally wrote must still be intact.
    assert state.get_chat("chat_priya", kotlin_db_path)["display_name"] == "Priya Nair"
    assert state.get_chat("chat_rohan", kotlin_db_path)["display_name"] == "Rohan Mehta"
    assert len(state.list_chats(kotlin_db_path)) == 3
    assert state.get_chat_cutoff("chat_priya", kotlin_db_path) == "2025-01-01T00:00:00"
    assert state.get_app_state(state.SELF_SENDER_LEARNED, kotlin_db_path) == "Priya Nair"
