"""Cross-language bundle proof, Kotlin -> Python direction (KT-08).

`MigrationGoldenParityTest.kt` (android/core) proves a bundle the real Python `export_bundle`
wrote imports in Kotlin with the same result. This module proves the mirror image: a bundle
written by the real Kotlin `exportBundle` imports through the real `src/migration.py`
`import_bundle` with the merge result the bundle's contents imply, and re-import is a no-op.

The fixture (`tests/fixtures/bundle_fixture_kotlin_written.cmsbackup`) is generated by
`android/core/src/fixtureGen/.../BundleFixtureGenerator.kt`:

    cd android && ./gradlew :core:generateBundleFixtureKotlinWritten

CI does not regenerate it; `MigrationKotlinFixtureTest` (run by the Android job) fails when the
committed file no longer matches what the Kotlin export produces. Placeholder data only.
"""

from __future__ import annotations

import json
import sqlite3
import zipfile
from pathlib import Path

import pytest

from src import migration, state

_FIXTURE = Path(__file__).parent / "fixtures" / "bundle_fixture_kotlin_written.cmsbackup"

pytestmark = pytest.mark.skipif(
    not _FIXTURE.exists(),
    reason="bundle_fixture_kotlin_written.cmsbackup not present -- run "
    "'cd android && ./gradlew :core:generateBundleFixtureKotlinWritten'",
)


def _rows(root: Path, sql: str) -> list[tuple]:
    con = sqlite3.connect(root / "data" / "sync_state.db")
    try:
        return sorted(con.execute(sql).fetchall())
    finally:
        con.close()


def test_bundle_layout_is_what_python_writes() -> None:
    with zipfile.ZipFile(_FIXTURE) as z:
        assert sorted(z.namelist()) == ["manifest.json", "settings.json", "sync_state.db"]
        manifest = json.loads(z.read("manifest.json"))
        settings = json.loads(z.read("settings.json"))
    assert manifest["schema_version"] == migration.BUNDLE_SCHEMA_VERSION
    assert manifest["counts"] == {"chats": 2, "runs": 2, "hashes": 2, "cutoffs": 1, "senders": 2}
    # Only allow-listed keys, no host, no credential-like key.
    assert set(settings) == {"chunk_size", "theme_mode", "imap_provider", "imap_port", "imap_email"}


def test_python_imports_a_kotlin_bundle_into_an_empty_install(tmp_path: Path) -> None:
    result = migration.import_bundle(tmp_path, _FIXTURE)
    assert result["ok"], result
    assert result["already_imported"] is False
    assert (result["chats_added"], result["runs_added"], result["hashes_added"]) == (2, 2, 2)
    assert (result["cutoffs_added"], result["senders_added"]) == (1, 2)
    # The host is derived from the provider, never read from the bundle.
    assert result["settings"]["imap_host"] != "evil.example.com"
    assert result["settings"]["imap_provider"] == "yahoo"
    assert "app_password" not in result["settings"]
    assert _rows(tmp_path, "SELECT chat_id, display_name FROM chats") == [
        ("chat-priya", "Priya Nair"), ("chat-vikram", "Vikram Rao"),
    ]
    assert _rows(tmp_path, "SELECT hash, chat_id FROM message_hashes") == [
        ("p1", "chat-priya"), ("p2", "chat-priya"),
    ]
    assert _rows(tmp_path, "SELECT chat_id, cutoff_ts FROM chat_cutoffs") == [("chat-priya", "2026-02-01T00:00:00")]
    assert _rows(tmp_path, "SELECT key, value FROM app_state") == [("owner_override", "Priya Nair")]
    # And every hash points at a run that exists here, under this install's ids.
    assert _rows(
        tmp_path,
        "SELECT COUNT(*) FROM message_hashes h JOIN sync_runs r ON r.run_id = h.run_id",
    ) == [(2,)]


def test_reimport_of_a_kotlin_bundle_changes_nothing(tmp_path: Path) -> None:
    migration.import_bundle(tmp_path, _FIXTURE)
    before = (_rows(tmp_path, "SELECT * FROM sync_runs"), _rows(tmp_path, "SELECT * FROM message_hashes"))
    again = migration.import_bundle(tmp_path, _FIXTURE)
    assert again["ok"] and again["already_imported"] is True
    assert (again["chats_added"], again["runs_added"], again["hashes_added"]) == (0, 0, 0)
    assert (_rows(tmp_path, "SELECT * FROM sync_runs"), _rows(tmp_path, "SELECT * FROM message_hashes")) == before


def test_import_into_an_install_with_local_history_never_overwrites_it(tmp_path: Path) -> None:
    db = tmp_path / "data" / "sync_state.db"
    db.parent.mkdir(parents=True)
    state.init_db(db)
    state.upsert_chat("chat-priya", "Priya (local name)", "local.txt", db_path=db)
    state.set_chat_cutoff("chat-priya", "2026-08-01", db_path=db)
    run = state.start_sync_run("chat-priya", db_path=db)
    state.insert_message_hashes([("local-only", "chat-priya", "2026-09-01T00:00:00", run)], db_path=db)

    result = migration.import_bundle(tmp_path, _FIXTURE)
    assert result["ok"], result
    # NEGATIVE: a local row always wins over an incoming one of the same name.
    assert _rows(tmp_path, "SELECT display_name FROM chats WHERE chat_id = 'chat-priya'") == [("Priya (local name)",)]
    assert _rows(tmp_path, "SELECT cutoff_ts FROM chat_cutoffs WHERE chat_id = 'chat-priya'") == [("2026-08-01T00:00:00",)]
    assert ("local-only",) in _rows(tmp_path, "SELECT hash FROM message_hashes")
    assert result["chats_added"] == 1  # only the chat this install did not have
