package com.chatmailsync.core.mail

import java.util.Base64

/**
 * Kotlin port of the RFC 2047 encoder Python's email package uses for a
 * utf-8 header: `email.charset.Charset('utf-8')` (header encoding SHORTEST)
 * with `email.quoprimime` and `email.base64mime`.
 *
 * Two entry points, matching the two ways the Python side reaches it:
 *  - [encodeWord] is `Charset.header_encode`, used by `email.utils.formataddr`
 *    for a non-ASCII display name: ONE encoded word, never split, whatever its
 *    length.
 *  - [encodeLines] is `Charset.header_encode_lines`, used by the header
 *    folder (see [Compat32Headers]): the value is cut, one code point at a
 *    time, into encoded words that each fit the line budget.
 *
 * In both, the encoding (base64 or quoted-printable) is chosen ONCE for the
 * whole value: base64 only when it is strictly shorter than quoted-printable,
 * otherwise quoted-printable. Every encoded word of a split value then uses
 * that same encoding.
 *
 * Quoted-printable here is `quoprimime`'s header map: letters, digits and
 * `-!*+/` stay literal, a space becomes `_`, every other byte is `=XX`
 * (upper-case hex) of the UTF-8 bytes.
 *
 * Goldens for this file are generated by the real Python email package
 * (`tools/generate_kotlin_core_golden_fixtures.py`, `mime_cases_golden.json`);
 * expected bytes are never written by hand.
 */
object Rfc2047 {
    private const val CHARSET = "utf-8"

    /** `len("utf-8") + RFC2047_CHROME_LEN`: the `=?utf-8?x?` + `?=` wrapper of one word. */
    private const val EXTRA = 5 + 7

    private val HEX = "0123456789ABCDEF".toCharArray()

    private fun qpSafe(b: Int): Boolean =
        (b >= 'a'.code && b <= 'z'.code) || (b >= 'A'.code && b <= 'Z'.code) ||
            (b >= '0'.code && b <= '9'.code) ||
            b == '-'.code || b == '!'.code || b == '*'.code || b == '+'.code || b == '/'.code

    private fun qpLength(bytes: ByteArray): Int {
        var n = 0
        for (raw in bytes) {
            val b = raw.toInt() and 0xFF
            n += if (qpSafe(b) || b == ' '.code) 1 else 3
        }
        return n
    }

    private fun base64Length(byteCount: Int): Int = ((byteCount + 2) / 3) * 4

    /** `Charset._get_encoder`: base64 only when strictly shorter than quoted-printable. */
    private fun useBase64(bytes: ByteArray): Boolean = base64Length(bytes.size) < qpLength(bytes)

    private fun encodeBytes(bytes: ByteArray, base64: Boolean): String {
        if (bytes.isEmpty()) return ""
        if (base64) return "=?$CHARSET?b?${Base64.getEncoder().encodeToString(bytes)}?="
        val sb = StringBuilder("=?$CHARSET?q?")
        for (raw in bytes) {
            val b = raw.toInt() and 0xFF
            when {
                b == ' '.code -> sb.append('_')
                qpSafe(b) -> sb.append(b.toChar())
                else -> sb.append('=').append(HEX[b shr 4]).append(HEX[b and 0x0F])
            }
        }
        return sb.append("?=").toString()
    }

    /** Mirrors `Charset('utf-8').header_encode(value)`: a single encoded word. */
    fun encodeWord(value: String): String {
        val bytes = value.toByteArray(Charsets.UTF_8)
        return encodeBytes(bytes, useBase64(bytes))
    }

    /**
     * Mirrors `Charset('utf-8').header_encode_lines(value, maxlengths)`.
     *
     * [nextMaxLength] is called once per line started (the first call gives the
     * room on the current line, later calls the room on continuation lines),
     * and those figures do not count the word wrapper. The first element of
     * the result is `null` when not even one character fits on the current
     * line. Every word is at most `maxLength` payload characters plus the
     * 12-character wrapper, i.e. within the 75-character RFC 2047 limit as
     * long as the budget is.
     */
    fun encodeLines(value: String, nextMaxLength: () -> Int): List<String?> {
        val all = value.toByteArray(Charsets.UTF_8)
        val base64 = useBase64(all)
        val lines = ArrayList<String?>()
        val current = StringBuilder()
        var maxLen = nextMaxLength() - EXTRA
        var i = 0
        while (i < value.length) {
            val cp = value.codePointAt(i)
            val ch = String(Character.toChars(cp))
            i += ch.length
            current.append(ch)
            val bytes = current.toString().toByteArray(Charsets.UTF_8)
            val length = if (base64) base64Length(bytes.size) else qpLength(bytes)
            if (length > maxLen) {
                // The last character does not fit: close the line without it.
                current.setLength(current.length - ch.length)
                if (lines.isEmpty() && current.isEmpty()) {
                    lines.add(null)
                } else {
                    lines.add(encodeBytes(current.toString().toByteArray(Charsets.UTF_8), base64))
                }
                current.setLength(0)
                current.append(ch)
                maxLen = nextMaxLength() - EXTRA
            }
        }
        lines.add(encodeBytes(current.toString().toByteArray(Charsets.UTF_8), base64))
        return lines
    }
}
