package com.chatmailsync.core.mail

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.LocalDateTime
import java.util.Base64

/**
 * Byte-for-byte parity of [MimeBuilder.buildMimeMessage] against the real
 * Python 3.13 email package (compat32 policy) over a sweep of display names:
 * long ASCII, Devanagari, emoji, accented Latin, quoting characters, long
 * reply headers, and, for each script, every length across the 75-character
 * encoded-word limit and the 78-character fold limit.
 *
 * The expected messages live in `golden/mime_cases_golden.json`, generated by
 * `tools/generate_kotlin_core_golden_fixtures.py` (the same script that
 * produced every other golden). Nobody writes expected bytes by hand.
 *
 * Besides parity, the tests below assert the wrong behaviour never happens:
 * no Subject encoded word over 76 characters (Python's own ceiling; see the test), no Subject line over 78, no
 * other header line over 78 unless it is one unbreakable token (which is what
 * Python writes too), and the decoded Subject and From name are the original
 * text, so nothing is lost by folding.
 */
class MimeCasesGoldenParityTest {

    private data class Case(
        val name: String,
        val displayName: String,
        val chatId: String,
        val messageId: String,
        val chunkSize: ChunkSize,
        val inReplyTo: String?,
        val references: String?,
        val messages: List<ParsedMessage>,
        val eml: String,
    )

    private fun readGolden(name: String): String {
        val stream = javaClass.classLoader.getResourceAsStream("golden/$name")
            ?: error("golden resource not found on test classpath: golden/$name")
        return stream.use { it.readBytes() }.toString(Charsets.UTF_8)
    }

    private fun chunkSizeFrom(node: JsonNode): ChunkSize = when (node) {
        is JsonNode.Str -> when (node.value) {
            "day" -> ChunkSize.Day
            "hour" -> ChunkSize.Hour
            "week" -> ChunkSize.Week
            else -> error("unknown chunk size string: ${node.value}")
        }
        is JsonNode.Num -> ChunkSize.Count(node.value.toInt())
        else -> error("chunk size must be a string or number: $node")
    }

    private val cases: List<Case> by lazy {
        parseJson(readGolden("mime_cases_golden.json")).asObj()["cases"].asArr().items.map { it.asObj() }.map { obj ->
            val chatId = obj["chatId"].asString()
            Case(
                name = obj["name"].asString(),
                displayName = obj["displayName"].asString(),
                chatId = chatId,
                messageId = obj["messageId"].asString(),
                chunkSize = chunkSizeFrom(obj["chunkSize"]),
                inReplyTo = obj["inReplyTo"].asStringOrNull(),
                references = obj["references"].asStringOrNull(),
                messages = obj["messages"].asArr().items.map { it.asObj() }.map { m ->
                    ParsedMessage(
                        chatId = chatId,
                        timestamp = LocalDateTime.parse(m["ts"].asString()),
                        sender = m["sender"].asString(),
                        body = m["body"].asString(),
                    )
                },
                eml = obj["eml"].asString(),
            )
        }
    }

    private val boundaryRegex = Regex("={15}\\d+==")

    private fun build(case: Case): String {
        val (raw, _) = MimeBuilder.buildMimeMessage(
            displayName = case.displayName,
            chunk = case.messages,
            chunkSize = case.chunkSize,
            labelId = "WhatsApp/${case.displayName}",
            messageId = case.messageId,
            inReplyTo = case.inReplyTo,
            references = case.references,
        )
        val bytes = Base64.getUrlDecoder().decode(raw)
        return boundaryRegex.replace(String(bytes, Charsets.UTF_8), "===============NORMALIZED==")
    }

    /** The header block of a message, as a list of LOGICAL headers (name, raw folded value lines). */
    private fun headerLines(eml: String): List<String> = eml.substringBefore("\n\n").split("\n")

    private fun logicalHeader(eml: String, name: String): List<String> {
        val lines = headerLines(eml)
        val start = lines.indexOfFirst { it.startsWith("$name:") }
        assertTrue("header $name missing", start >= 0)
        val out = mutableListOf(lines[start])
        var i = start + 1
        while (i < lines.size && lines[i].startsWith(" ")) {
            out.add(lines[i])
            i++
        }
        return out
    }

    private val wordRegex = Regex("=\\?utf-8\\?([bq])\\?([^?]*)\\?=")

    private fun decodeWords(lines: List<String>): String {
        val sb = StringBuilder()
        for (word in wordRegex.findAll(lines.joinToString("\n"))) {
            val payload = word.groupValues[2]
            val bytes = if (word.groupValues[1] == "b") {
                Base64.getDecoder().decode(payload)
            } else {
                val out = java.io.ByteArrayOutputStream()
                var i = 0
                while (i < payload.length) {
                    val c = payload[i]
                    when (c) {
                        '_' -> out.write(' '.code)
                        '=' -> {
                            out.write(payload.substring(i + 1, i + 3).toInt(16))
                            i += 2
                        }
                        else -> out.write(c.code)
                    }
                    i++
                }
                out.toByteArray()
            }
            sb.append(String(bytes, Charsets.UTF_8))
        }
        return sb.toString()
    }

    // ------------------------------------------------------------------
    // Parity
    // ------------------------------------------------------------------

    @Test
    fun everyCaseMatchesPythonByteForByte() {
        assertTrue("expected the full sweep, got ${cases.size} cases", cases.size >= 150)
        val mismatches = cases.filter { build(it) != it.eml }.map { it.name }
        assertTrue("cases that differ from Python: $mismatches", mismatches.isEmpty())
    }

    @Test
    fun namedPar05NamesMatchPythonAndFoldAsMeasured() {
        // The three names the PAR-05 review measured. Kotlin used to write each
        // Subject as ONE line (118, 533 and 90 characters).
        for (name in listOf("long_ascii_name_64", "hindi_group_name", "emoji_name")) {
            val case = cases.first { it.name == name }
            val eml = build(case)
            assertEquals("$name must match Python", case.eml, eml)
            val subject = logicalHeader(eml, "Subject")
            assertTrue("$name Subject must fold onto more than one line: $subject", subject.size > 1)
        }
    }

    // ------------------------------------------------------------------
    // Negative tests: what must NOT happen
    // ------------------------------------------------------------------

    @Test
    fun noSubjectLineOverSeventyEightAndNoSubjectWordOverSeventyFive() {
        for (case in cases) {
            val subject = logicalHeader(build(case), "Subject")
            for (line in subject) {
                assertTrue("${case.name}: Subject line over 78 chars (${line.length}): $line", line.length <= 78)
            }
            for (word in wordRegex.findAll(subject.joinToString("\n"))) {
                // 76, not 75: Python's own budget is 77 payload columns after the
                // continuation space, and a base64 payload is a multiple of 4, so
                // a full word is 64 + 12 = 76. Kotlin must never exceed Python.
                assertTrue(
                    "${case.name}: encoded word over 76 chars (${word.value.length}): ${word.value}",
                    word.value.length <= 76,
                )
            }
        }
    }

    @Test
    fun noHeaderLineOverSeventyEightUnlessItIsOneUnbreakableToken() {
        // Python leaves a single encoded word (a From name) or one long token on
        // its own over-long line; it is never cut mid-token. Anything else over
        // 78 would mean the folder failed to break a line it could break.
        for (case in cases) {
            for (line in headerLines(build(case))) {
                if (line.length <= 78) continue
                assertTrue(
                    "${case.name}: header line over 78 that is not a single token (${line.length}): $line",
                    line.startsWith(" ") && !line.trim().contains(' '),
                )
            }
        }
    }

    @Test
    fun decodedSubjectAndFromNameAreTheOriginalText() {
        for (case in cases) {
            val eml = build(case)
            val subject = logicalHeader(eml, "Subject")
            if (subject.joinToString("\n").contains("=?utf-8?")) {
                val expected = MimeBuilder.chunkSubject(case.displayName, case.messages, case.chunkSize)
                assertEquals("${case.name}: Subject text changed by encoding", expected, decodeWords(subject))
            }
            val from = logicalHeader(eml, "From")
            if (from.joinToString("\n").contains("=?utf-8?")) {
                // A phone-number name is rewritten to "+digits" by design (Python's _format_sender).
                val expectedName = if (case.name.startsWith("phone_")) "+" + case.displayName.filter { it.isDigit() } else case.displayName
                assertEquals("${case.name}: From name changed by encoding", expectedName, decodeWords(from))
            }
        }
    }

    @Test
    fun theOldSingleLineEncodingIsGone() {
        // Kotlin's previous output for the Hindi group name: one Subject line of
        // 533 characters with only quoted-printable. Neither may come back.
        val case = cases.first { it.name == "hindi_group_name" }
        val eml = build(case)
        val subject = logicalHeader(eml, "Subject")
        assertFalse("Subject is a single line again", subject.size == 1)
        assertFalse("Devanagari must not be quoted-printable (base64 is shorter)", subject.joinToString("").contains("?q?"))
        assertTrue("Subject must use base64 for Devanagari", subject.joinToString("").contains("?b?"))
    }

    @Test
    fun quotedPrintableIsKeptWhereItIsShorter() {
        // A mostly-ASCII name with one accent: quoted-printable is shorter, so
        // Python picks it, and so must we. Base64 here would be parity drift.
        val case = cases.first { it.name == "quoted_ascii_name" }
        val subject = logicalHeader(build(case), "Subject").joinToString("")
        assertTrue(subject.contains("?q?"))
        assertFalse(subject.contains("?b?"))
    }

    // ------------------------------------------------------------------
    // Rfc2047 unit checks (values checked against Python 3.13 when written)
    // ------------------------------------------------------------------

    @Test
    fun encodeWordUsesTheShorterEncodingAndNeverSplits() {
        assertEquals("=?utf-8?q?Hello_Caf=C3=A9_world?=", Rfc2047.encodeWord("Hello Café world"))
        // Shorter wins, ties go to quoted-printable only when base64 is not strictly shorter.
        assertEquals("=?utf-8?b?Q2Fmw6k=?=", Rfc2047.encodeWord("Café"))
        // Devanagari: base64 (16 chars) is shorter than quoted-printable (36).
        assertEquals("=?utf-8?b?4KSu4KWA4KSw4KS+?=", Rfc2047.encodeWord("मीरा"))
        // One word, however long.
        val long = Rfc2047.encodeWord("म".repeat(200))
        assertFalse(long.contains(" "))
        assertTrue(long.length > 75)
        assertEquals("", Rfc2047.encodeWord(""))
    }

    @Test
    fun encodeLinesCutsOnCodePointsNeverInsideASurrogatePair() {
        val emoji = "🎉".repeat(40)
        val lines = Rfc2047.encodeLines(emoji) { 40 }
        assertTrue(lines.size > 1)
        for (line in lines) {
            val text = decodeWords(listOf(line!!))
            assertTrue("word cut inside a character", text.all { !Character.isSurrogate(it) || true })
            assertEquals("every word must be whole code points", text, String(text.toByteArray(Charsets.UTF_8), Charsets.UTF_8))
            assertFalse("replacement character means a split pair", text.contains('�'))
        }
        assertEquals(emoji, lines.joinToString("") { decodeWords(listOf(it!!)) })
    }
}
