package com.chatmailsync.core.mail

import org.junit.Assert.assertEquals
import org.junit.Test
import java.time.LocalDateTime
import java.util.Base64

/**
 * Phase 1 exit criterion: [MimeBuilder.buildMimeMessage] and
 * [indexBytes]/[buildIndex] must produce byte-for-byte identical output to
 * Python's `_build_mime_message`/`mail_index.build_index`/`index_bytes` for
 * the same fixed input, once the one genuinely non-deterministic token (the
 * MIME boundary -- both sides use a random one) is normalized to the same
 * placeholder on both sides.
 *
 * The golden files under `src/test/resources/golden/` were generated by
 * running the real Python functions via
 * `tools/generate_kotlin_core_golden_fixtures.py` against the exact same
 * fixture built below -- see that script's FIXTURE_* constants, which this
 * test's [fixtureChunk]/constants must keep in sync with. No live network,
 * no Chaquopy, no Python runtime is used here: the golden files are static
 * resources checked into the repo, refreshed by re-running that script only
 * when the Python builder functions themselves change.
 *
 * There is no equivalent standalone Python test for this comparison (it is
 * inherently cross-language); this file is new, not a port of an existing
 * Python test.
 */
class MimeGoldenParityTest {

    private val displayName = "Meera Iyer"
    private val chatId = "test_chat"
    private val messageId = "<golden-fixture-anchor@local>"
    private val labelId = "WhatsApp/Meera Iyer"

    private fun fixtureChunk(): List<ParsedMessage> = listOf(
        ParsedMessage(
            chatId = chatId,
            timestamp = LocalDateTime.of(2019, 5, 3, 10, 15, 0),
            sender = "Meera Iyer",
            body = "hello from the past",
        ),
        ParsedMessage(
            chatId = chatId,
            timestamp = LocalDateTime.of(2019, 5, 3, 10, 16, 0),
            sender = "Kavya Menon",
            body = "line one\nline two continuation",
        ),
    )

    private val boundaryRegex = Regex("={15}\\d+==")

    private fun normalizeBoundary(bytes: ByteArray): ByteArray =
        boundaryRegex.replace(String(bytes, Charsets.UTF_8), "===============NORMALIZED==").toByteArray(Charsets.UTF_8)

    private fun readGoldenResource(name: String): ByteArray {
        val stream = javaClass.classLoader.getResourceAsStream("golden/$name")
            ?: error("golden resource not found on test classpath: golden/$name")
        return stream.use { it.readBytes() }
    }

    @Test
    fun mimeMessageMatchesPythonByteForByteAfterBoundaryNormalization() {
        val chunk = fixtureChunk()
        val (raw, returnedLabelId) = MimeBuilder.buildMimeMessage(
            displayName = displayName,
            chunk = chunk,
            chunkSize = ChunkSize.Day,
            labelId = labelId,
            messageId = messageId,
        )
        assertEquals(labelId, returnedLabelId)

        val actualBytes = Base64.getUrlDecoder().decode(raw)
        val actualNormalized = normalizeBoundary(actualBytes)
        val expected = readGoldenResource("mime_message_golden.eml")

        assertEquals(String(expected, Charsets.UTF_8), String(actualNormalized, Charsets.UTF_8))
    }

    @Test
    fun indexJsonMatchesPythonByteForByte() {
        val chunk = fixtureChunk()
        val index = buildIndex(
            displayName = displayName,
            chunk = chunk,
            chunkSize = ChunkSize.Day,
            messageId = messageId,
        )
        val actual = indexBytes(index)
        val expected = readGoldenResource("index_golden.json")

        assertEquals(String(expected, Charsets.UTF_8), String(actual, Charsets.UTF_8))
    }
}
