package com.chatmailsync.core.mail

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * Cross-language database-compatibility proof: [StateRepository]/[StateDb]
 * (via [SqliteJdbcStateDb]) must be able to open, read, and write a
 * `sync_state.db` file that the *real* `src/state.py` created, with no
 * migration surprises and no `PRAGMA user_version` disagreement.
 *
 * `state_fixture_python_written.db` (`android/core/src/test/resources/golden/`)
 * was generated by `tools/generate_kotlin_core_golden_fixtures.py`'s
 * `generate_state_db_golden()`, which calls the real `state.py` functions
 * (`init_db`, `upsert_chat`, `update_chat_gmail_ids`, `start_sync_run`,
 * `insert_message_hashes`, `complete_sync_run`, `fail_sync_run`,
 * `set_chat_cutoff`, `record_chat_senders`, `set_app_state`) with
 * `state._now()` monkeypatched to a single fixed literal
 * (`"2025-03-14T09:40:00"`) for the whole run, so every stored
 * created_at/updated_at/started_at/completed_at/set_at value is that exact
 * literal -- see that function's doc comment for why this monkeypatch was
 * necessary for the generator to be deterministic run-to-run at all (not
 * just byte-for-byte: without it, timestamp columns differed on every
 * regeneration).
 *
 * This test proves BOTH directions this PR's brief requires:
 *  - Python -> Kotlin: copies the committed fixture into a real temp file
 *    and reads every row back through [StateRepository], asserting the
 *    values match exactly what the generator wrote.
 *  - Kotlin -> that same file: after reading, writes further rows into the
 *    SAME file through [StateRepository] (a new chat, a new completed sync
 *    run, a hash, a cutoff) and reads them back, proving Kotlin can extend a
 *    Python-written database without disturbing what Python wrote (the
 *    original chats/runs/hashes/cutoff/senders/app_state are re-asserted
 *    unchanged afterwards).
 *
 * The reverse direction (Python reading a Kotlin-written database) is
 * proven on the Python side by a `pytest.mark.skipif`-gated test reading a
 * fixture from a one-off Kotlin `fixtureGen` entry point -- see the PR body.
 *
 * `state_fixture_python_written.db` is a binary SQLite file and shows as
 * "Bin" in `git diff`/`git show` -- that is expected and not a mistake.
 */
class StateDbGoldenParityTest {

    @get:Rule
    val tmp = TemporaryFolder()

    private val frozenNow = "2025-03-14T09:40:00"

    private fun copyFixtureToTempFile(): File {
        val stream = javaClass.classLoader.getResourceAsStream("golden/state_fixture_python_written.db")
            ?: error("golden resource not found on test classpath: golden/state_fixture_python_written.db")
        val out = tmp.newFile("state_fixture_python_written.db")
        stream.use { input -> out.outputStream().use { output -> input.copyTo(output) } }
        return out
    }

    @Test
    fun readsEveryRowThePythonGeneratorWroteExactly() {
        val dbFile = copyFixtureToTempFile()
        val repo = StateRepository { SqliteJdbcStateDb(dbFile.absolutePath) }

        val meera = repo.getChat("chat_meera")
        assertEquals("Meera Iyer", meera?.displayName)
        assertEquals("Meera Iyer.txt", meera?.sourceFilename)
        assertEquals("thread-1", meera?.gmailThreadId)
        assertEquals("WhatsApp/Meera Iyer", meera?.gmailLabelId)
        assertEquals("<golden-anchor@local>", meera?.anchorMessageId)
        assertEquals(frozenNow, meera?.createdAt)
        assertEquals(frozenNow, meera?.updatedAt)

        val team = repo.getChat("chat_team")
        assertEquals("Team Sales", team?.displayName)
        assertNull(team?.gmailThreadId)

        val chats = repo.listChats()
        assertEquals(2, chats.size)

        val lastRun = repo.getLastSuccessfulRun("chat_meera")
        assertEquals("complete", lastRun?.status)
        assertEquals("manual", lastRun?.trigger)
        assertEquals("2025-03-14T09:41:30", lastRun?.lastSyncedTs)
        assertEquals(2, lastRun?.messagesParsed)
        assertEquals(2, lastRun?.messagesSynced)
        assertEquals(0, lastRun?.messagesSkipped)
        assertEquals(0, lastRun?.messagesCutoff)
        assertEquals(frozenNow, lastRun?.startedAt)
        assertEquals(frozenNow, lastRun?.completedAt)

        val h1 = StateRepository.computeMessageHash(
            "chat_meera", "2025-03-14T09:41:00", "Meera Iyer", "hello from the golden fixture",
        )
        val h2 = StateRepository.computeMessageHash(
            "chat_meera", "2025-03-14T09:41:30", "Rohan Mehta", "line one\nline two",
        )
        assertTrue(repo.hashExists(h1))
        assertTrue(repo.hashExists(h2))
        assertEquals(setOf(h1, h2), repo.getHashesForRun(lastRun!!.runId))
        assertEquals(h2, lastRun.lastSyncedHash)

        val pending = repo.getPendingRuns()
        assertTrue("run2 (chat_team) failed, so it must not still be pending", pending.none { it.chatId == "chat_team" })

        val teamRuns = repo.getRecentRuns(days = 3650).filter { it.chatId == "chat_team" }
        assertEquals(1, teamRuns.size)
        assertEquals("failed", teamRuns.first().status)
        assertEquals("watched_folder", teamRuns.first().trigger)
        assertEquals("golden fixture: simulated network error", teamRuns.first().errorMessage)

        assertEquals("2025-01-01T00:00:00", repo.getChatCutoff("chat_meera"))
        assertNull(repo.getChatCutoff("chat_team"))

        val senders = repo.listChatSenders("chat_meera").associateBy { it.sender }
        assertEquals(1, senders["Meera Iyer"]?.msgCount)
        assertEquals(1, senders["Rohan Mehta"]?.msgCount)
        assertEquals(0, senders["Priya Nair"]?.msgCount)

        assertEquals("Priya Nair", repo.getAppState(StateRepository.SELF_SENDER_LEARNED))
    }

    @Test
    fun kotlinCanExtendAPythonWrittenDatabaseWithoutDisturbingWhatPythonWrote() {
        val dbFile = copyFixtureToTempFile()
        val repo = StateRepository { SqliteJdbcStateDb(dbFile.absolutePath) }

        // Write: a brand-new chat, a completed run for it, a hash, and a
        // cutoff -- all through the ordinary Kotlin write path.
        repo.upsertChat("chat_kavya", "Kavya Menon", "Kavya Menon.txt")
        val newRun = repo.startSyncRun("chat_kavya", trigger = "manual")
        val newHash = StateRepository.computeMessageHash(
            "chat_kavya", "2025-04-01T08:00:00", "Kavya Menon", "written by kotlin",
        )
        repo.insertMessageHashes(
            listOf(StateRepository.HashEntry(newHash, "chat_kavya", "2025-04-01T08:00:00", newRun)),
        )
        repo.completeSyncRun(
            newRun,
            lastSyncedTs = "2025-04-01T08:00:00",
            lastSyncedHash = newHash,
            messagesParsed = 1,
            messagesSynced = 1,
            messagesSkipped = 0,
        )
        repo.setChatCutoff("chat_kavya", "2025-04-01")

        // Read back what Kotlin just wrote.
        val kavya = repo.getChat("chat_kavya")
        assertEquals("Kavya Menon", kavya?.displayName)
        assertTrue(repo.hashExists(newHash))
        assertEquals("2025-04-01T00:00:00", repo.getChatCutoff("chat_kavya"))
        val kavyaRun = repo.getLastSuccessfulRun("chat_kavya")
        assertEquals("complete", kavyaRun?.status)

        // Re-read everything the Python generator originally wrote, proving
        // it is untouched by the writes above.
        assertEquals("Meera Iyer", repo.getChat("chat_meera")?.displayName)
        assertEquals("Team Sales", repo.getChat("chat_team")?.displayName)
        assertEquals(3, repo.listChats().size)
        assertEquals("2025-01-01T00:00:00", repo.getChatCutoff("chat_meera"))
        assertEquals("Priya Nair", repo.getAppState(StateRepository.SELF_SENDER_LEARNED))
        val h1 = StateRepository.computeMessageHash(
            "chat_meera", "2025-03-14T09:41:00", "Meera Iyer", "hello from the golden fixture",
        )
        assertTrue(repo.hashExists(h1))
    }
}
